typography_spectrum: 0.32325552799738944
color:
  brandColors:
    - '#ffc90d'
    - '#fefefe'
    - '#000000'
    - '#9ad9ea'
    - '#7d7d7d'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.019774930318817496
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8c30c0f8-3113-4b0b-8329-4d222266b6cc.jpg
name: Downtown Rising
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eee1a938-29d3-4e51-aed9-c5650e4a3fbf.jpg
title: 'Food, Music & Art '
purpose: []
