name: Downtown Rising
favicon: null
layout_spectrum: 0.019774930318817496
typography_spectrum: 0.32325552799738944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffc90d'
    - '#fefefe'
    - '#000000'
    - '#9ad9ea'
    - '#7d7d7d'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
